"""sd - the SigDeck command line interface."""

import argparse
import sys
from pathlib import Path

from .keys import (armor_public, armor_secret, generate_seed, load_public,
                   load_secret, save_armored)
from . import qr


def _do_keygen(args):
    seed = generate_seed()
    save_armored(args.out, armor_secret(seed, comment="generated by sd"))
    pub_path = Path(args.out).with_suffix(".pub")
    save_armored(pub_path, armor_public(public_bytes(seed)))
    print(f"wrote {args.out} and {pub_path}")
    return 0


def public_bytes(seed):
    from .keys import public_bytes as _pb
    return _pb(seed)


def _do_pub(args):
    seed = load_secret(args.key)
    save_armored(args.output, armor_public(public_bytes(seed)))
    print(f"wrote {args.output}")
    return 0


def _do_sign(args):
    from .sign import sign_file, detached_path
    seed = load_secret(args.key)
    sig = sign_file(Path(args.file), seed)
    out = Path(args.output or detached_path(Path(args.file)).name)
    out.write_bytes(sig)
    print(f"wrote {out}")
    return 0


def _do_verify(args):
    from .verify import verify_file
    public = load_public(args.pub)
    ok = verify_file(Path(args.sig), Path(args.file), public)
