"""sd - the SigDeck command line interface."""

import argparse
import sys
from pathlib import Path

from .keys import (armor_public, armor_secret, generate_seed, load_public,
                   load_secret, save_armored)
from . import qr


def _do_keygen(args):
    seed = generate_seed()
    save_armored(args.out, armor_secret(seed, comment="generated by sd"))
    pub_path = Path(args.out).with_suffix(".pub")
    save_armored(pub_path, armor_public(public_bytes(seed)))
    print(f"wrote {args.out} and {pub_path}")
    return 0


def public_bytes(seed):
    from .keys import public_bytes as _pb
    return _pb(seed)


def _do_pub(args):
    seed = load_secret(args.key)
    save_armored(args.output, armor_public(public_bytes(seed)))
    print(f"wrote {args.output}")
