"""sd - the SigDeck command line interface."""

import argparse
import sys
from pathlib import Path

from .keys import (armor_public, armor_secret, generate_seed, load_public,
                   load_secret, save_armored)
from . import qr


def _do_keygen(args):
    seed = generate_seed()
    save_armored(args.out, armor_secret(seed, comment="generated by sd"))
    pub_path = Path(args.out).with_suffix(".pub")
    save_armored(pub_path, armor_public(public_bytes(seed)))
    print(f"wrote {args.out} and {pub_path}")
    return 0


def public_bytes(seed):
    from .keys import public_bytes as _pb
    return _pb(seed)


def _do_pub(args):
    seed = load_secret(args.key)
    save_armored(args.output, armor_public(public_bytes(seed)))
    print(f"wrote {args.output}")
    return 0


def _do_sign(args):
    from .sign import sign_file, detached_path
    seed = load_secret(args.key)
    sig = sign_file(Path(args.file), seed)
    out = Path(args.output or detached_path(Path(args.file)).name)
    out.write_bytes(sig)
    print(f"wrote {out}")
    return 0


def _do_verify(args):
    from .verify import verify_file
    public = load_public(args.pub)
    ok = verify_file(Path(args.sig), Path(args.file), public)
    print("Verified" if ok else "FAILED")
    return 0 if ok else 1


def _do_export_qr(args):
    if args.key:
        seed = load_secret(args.key)
        payload = qr.encode_key(public_bytes(seed))
    else:
        public = load_public(args.pub)
        payload = qr.encode_key(public)
    Path(args.out).write_text(payload, "utf-8")
    print(f"wrote {args.out}")
    return 0


def _do_import_qr(args):
    payload = Path(args.payload).read_text("utf-8").strip()
    kind, data = qr.decode(payload)
    print(f"decoded {kind} payload, {len(data)} bytes")
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(prog="sd")
    sub = ap.add_subparsers(dest="cmd", required=True)

    pk = sub.add_parser("keygen", help="create a new key pair")
    pk.add_argument("--out", default="signing.key")

    pp = sub.add_parser("pub", help="export the public key")
    pp.add_argument("--key", default="signing.key")
    pp.add_argument("--output", default="signing.pub")

    ps = sub.add_parser("sign", help="sign a file")
    ps.add_argument("file")
    ps.add_argument("--key", default="signing.key")
    ps.add_argument("--output", default=None)

    pv = sub.add_parser("verify", help="verify a signature")
    pv.add_argument("file")
    pv.add_argument("--sig", default=None)
    pv.add_argument("--pub", default="signing.pub")

    pe = sub.add_parser("export-qr", help="export a public key as a QR payload")
    pe.add_argument("--key", default=None)
    pe.add_argument("--pub", default="signing.pub")
    pe.add_argument("--out", default="key.qr.txt")

    pi = sub.add_parser("import-qr", help="decode a QR payload")
    pi.add_argument("payload")

